import type { NextPage } from "next";
import { useEffect } from "react";
import Button from "../components/Button";
import Step from "../components/Step";
import Head from "next/head";

const Home: NextPage = () => {
  useEffect(() => {
    const circles = document.getElementsByClassName("circle");

    circles[0].classList.add("active");

    const disabled = document.querySelector("#prev")?.attributes.getNamedItem("disabled")
    console.log(disabled?.name)
  }, []);

  const steps = [{name: "1"},{name: "2"},{name: "3"},{name: "4"}];

  

  return (
    <div>
      <Head>
        <title>Create Progress Steps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="title">Progress Steps</h1>
        <div className="container">
          <div className="progress-container">
            <div className="progress" id="progress"></div>
            {steps.map((item)=> <Step key={item.name} name={item.name} />)}
          </div>
          <Button id="prev" name="Prev" disabled={true} />
          <Button id="next" name="Next" />
        </div>
      </main>
    </div>
  );
};

export default Home;
