import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Progress Steps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="title">Create Progress Steps</h1>
        <div className="container">
          <div className="progress-container">
            <div className="progress" id="progress"></div>
            <div className="circle active">1</div>
            <div className="circle">2</div>
            <div className="circle">3</div>
            <div className="circle">4</div>
          </div>
          <button className="btn" id="prev" disabled>
            Prev
          </button>
          <button className="btn" id="next">
            Next
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
